Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/08/2020
Var
par: inteiro


Inicio
      para par de 100 ate 1 passo -1 faca
         se par mod 2 = 0 entao
         escreval(par)
         fimse
      fimpara
      escreval("Esse são os números Pares")
Fimalgoritmo